# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: Default
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
  - deployment: VMDeploy
    displayName: web
    pool: Default
    strategy:
      runOnce:
        deploy:
          steps:
            - task: Docker@2
              displayName: Run the container
              inputs:
                command: start
              
    environment:
      name: GastroBudget
      resourceType: VirtualMachine
      tags: web
