# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: BuildAndPush
  displayName: Build and Push services
  jobs:
  - job: Build
    displayName: Build services
    pool: Default
    steps:
      - task: DockerCompose@0
        displayName: Build services
        inputs:
          action: 'Build services'
          containerregistrytype: 'Azure Container Registry'
          azureSubscription: '$(AZ_SUBSCRIPTION)'
          azureContainerRegistry: '$(REGISTRY_HOST)'
          dockerComposeFile: '$(Build.SourcesDirectory)/docker-compose.yml'
          dockerComposePath: '/usr/local/bin/docker-compose'
          projectName: gastrobudget-nextjs
          dockerComposeFileArgs: |
            REGISTRY_HOST=$(REGISTRY_HOST)
            NGINX_PORT=$(NGINX_PORT)
            NEXT_PUBLIC_YELP_API_KEY=$(YELP_API_KEY)
            NEXT_PUBLIC_GEOAPIFY_API_KEY=$(GEOAPIFY_API_KEY)
          includeLatestTag: true
          additionalImageTags: $(tag)
  - job: Push
    displayName: Push services
    pool: Default
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'acr-connection'
          command: 'login'

      - task: DockerCompose@0
        displayName: Push services
        inputs:
          action: Push services
          azureSubscription: $(AZ_SUBSCRIPTION)
          azureContainerRegistry: $(AZ_REGISTRY)
          dockerComposeFile: '$(Build.SourcesDirectory)/docker-compose.yml'
          dockerComposePath: '/usr/local/bin/docker-compose'
          projectName: gastrobudget-nextjs
          additionalImageTags: $(tag)
          qualifyImageNames: true
          dockerComposeFileArgs: |
            REGISTRY_HOST=$(REGISTRY_HOST)

- stage: Deploy
  displayName: Deploy services
  jobs:
  - deployment: VMDeploy
    displayName: Deploy
    pool: Default
    environment:
      name: GastroBudget
      resourceType: VirtualMachine
      tags: web
    strategy:
      runOnce:
        deploy:
          steps:
            - task: Docker@2
              inputs:
                containerRegistry: 'acr-connection'
                command: 'login'

            - task: DockerCompose@0
              displayName: Run services
              inputs:
                action: Run services
                azureSubscription: $(AZ_SUBSCRIPTION)
                azureContainerRegistry: $(AZ_REGISTRY)
                dockerComposeFile: '$(Build.SourcesDirectory)/docker-compose.yml'
                dockerComposePath: '/usr/local/bin/docker-compose'
                projectName: gastrobudget-nextjs
                qualifyImageNames: true
                additionalImageTags: $(tag)
                buildImages: true
                abortOnContainerExit: true
                detached: false
                dockerComposeFileArgs: |
                  REGISTRY_HOST=$(REGISTRY_HOST)