# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerComposeFilePath: '$(Build.SourcesDirectory)/docker-compose.yml'
  artifactName : drop

stages:
- stage: BuildAndPush
  displayName: Build and Push services
  jobs:
  - job: Build
    displayName: Build and Push services
    pool: Default
    steps:
      - task: DockerCompose@0
        displayName: Build services
        inputs:
          containerregistrytype: 'Container Registry'
          dockerRegistryEndpoint: '$(AZ_ENDPOINT)'
          dockerComposeFile: '$(dockerComposeFilePath)'
          dockerComposeFileArgs: |
            REGISTRY_HOST=$(REGISTRY_HOST)
            NGINX_PORT=$(NGINX_PORT)
            NEXT_PUBLIC_YELP_API_KEY=$(YELP_API_KEY)
            NEXT_PUBLIC_GEOAPIFY_API_KEY=$(GEOAPIFY_API_KEY)
          projectName: 'gastrobudget-nextjs'
          action: 'Build services'
          additionalImageTags: '$(tag)'
          includeLatestTag: true
          dockerComposePath: '/usr/local/bin/docker-compose'

      - task: DockerCompose@0
        displayName: Push services
        inputs:
          containerregistrytype: 'Container Registry'
          dockerRegistryEndpoint: '$(AZ_ENDPOINT)'
          dockerComposeFile: '$(dockerComposeFilePath)'
          dockerComposeFileArgs: 'REGISTRY_HOST=$(REGISTRY_HOST)'
          projectName: 'gastrobudget-nextjs'
          action: 'Push services'
          additionalImageTags: '$(tag)'
          includeLatestTag: true
          dockerComposePath: '/usr/local/bin/docker-compose'

      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)'
          Contents: '**/docker-compose.yml'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: '$(artifactName)'
          publishLocation: 'Container'

- stage: VMDeploy
  displayName: Deploy services
  jobs:
  - deployment: VMDeploy
    displayName: Deploy
    pool: Default
    environment:
      name: GastroBudget
      resourceType: VirtualMachine
      tags: web
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadBuildArtifacts@0
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: '$(artifactName)'
                downloadPath: '$(Agent.BuildDirectory)'

            - task: DockerCompose@0
              displayName: Run services
              inputs:
                containerregistrytype: 'Container Registry'
                dockerRegistryEndpoint: '$(AZ_ENDPOINT)'
                dockerComposeFile: '$(Agent.BuildDirectory)/$(artifactName)/docker-compose.yml'
                dockerComposeFileArgs: 'REGISTRY_HOST=$(REGISTRY_HOST)'
                projectName: 'gastrobudget-nextjs'
                action: 'Run services'
                buildImages: false
                detached: true
                dockerComposePath: '/usr/local/bin/docker-compose'
