version: "3.8"
services:
  web:
    image: ${REGISTRY_HOST}/gastrobudget-nextjs-web
    build:
      context: ./
  nginx:
    image: ${REGISTRY_HOST}/gastrobudget-nextjs-nginx
    restart: always
    build:
      context: ./nginx
    environment:
      - NGINX_PORT=${NGINX_PORT}
    ports:
      - "${NGINX_PORT}:80"
